### ISSUE TITLE
Broken on mobile

### ISSUE THREAD

**Issue by ThatOneCalculator** [afnzmn/afnzmn.github.io#1]
Screen recording:
https://pool.jortage.com/voringme/misskey/ccd6f765-e5b3-4ebb-b04d-2f19d28c1e8f.mp4

**Comment by afnzmn** [comment]
Wait wow you actually found this LMAO
It's still a work in progress, and I'm still just learning how to code lol
Thanks for checking my stuff out tho :)

**Comment by ThatOneCalculator** [comment]
Im everywhere 🕴️

**Comment by afnzmn** [comment]
Fixed in redesigned website.
